### ISSUE TITLE
Think about field experiment on UiO Psych

### ISSUE THREAD

**Issue by troettge** [troettge/Research-NORRN#10]

**Comment by troettge** [comment]
Maybe trivial, but for the intervention to be informative, it would need to be a minor manipulation, so groups would basically do the same thing except for a minor detail. If you put groups into completely different scenarios (e.g. escape room vs. talk), it would be difficult to pin down causality.

**Comment by julienmayor** [comment]
Yes - and it will be difficult to ensure that both groups have the same information (quality and quantity). 
Coupled with the fact that it looks like the PSI winter seminar will be restricted to 4h for the Open Science part (including prize ceremony, etc) - today's meeting suggested it will converge towards talk + discussions only, hence it does not offer the possibility of running an actual study. 
I thus suggest to close down this issue - as it is unfeasible.
