### ISSUE TITLE
Think about issues related to NO epidemiological data

### ISSUE THREAD

**Issue by troettge** [troettge/Research-NORRN#11]

**Comment by troettge** [comment]
Some unordered thoughts:

- I think it would useful to involve at least 1 or 2 experts that have worked with these kind of data from different angles
- the uniqueness of dataset and high impact on research landscape is a good argument to generate broad interest
- as soon as we have the data, we can approach the press to broadcast our message

A possible workflow could look like this:
- identify automatic way to identify target articles (e.g. by search string related to data set in abstract or title using web of science)
- identify target estimands (e.g. open raw data, open processed data, open scripts, open materials/protocols, preregistration)
- if the sample is really large, we can do a two-part analysis. (a) An automated analysis on the whole sample, screening for target search strings and (b) a manual analysis, screening random sample of articles for cues to transparent practices.

**Comment by julienmayor** [comment]
Here is the cohort that I had in mind: https://www.fhi.no/en/studies/moba/ - 950 articles published as of last month...

**Comment by troettge** [comment]
Given the strict publication [guidelines](https://www.fhi.no/globalassets/dokumenterfiler/studier/den-norske-mor-far-og-barn--undersokelsenmoba/info-til-forskere/publication_guidelines_moba.pdf), these should be easy to identify really.
